### ISSUE TITLE
Automatic ticket deletion

### ISSUE THREAD

**Issue by kforbro** [Fear-and-Terror-EU-Programming-Team/fear-and-terror-ticket-bot#1]
I suggest to make automatic deletion of the ticket after saving the transcript.

**Comment by w4rum** [comment]
We intentionally put that behind a manual confirmation to allow the ticket to be re-opened. With automatic deletion, closing a ticket would immediately lead to its deletion, which is not what we want for our use case.

If you are interested in this feature, feel free to add this as a configuration option. Just be warned that this is one of our oldest and most spaghetti-code-ish projects. The code is unnecessarily convoluted and might be a bit hard to get into.
