### ISSUE TITLE
Small suggestion

### ISSUE THREAD

**Issue by ClaraCrazy** [Fear-and-Terror-EU-Programming-Team/fear-and-terror-ticket-bot#3]
Hey. I know you said this is not actively maintained anymore but would it be possible for you to do me a small favor and change something as I dont really know that much about discord bots?

Instead of having roles "BOT_TICKET_MANAGER_ROLES" just check if the user has admin permissions to create a new ticket menu.

I would be really grateful if you could do that. <3

**Comment by w4rum** [comment]
Sorry, implementing that change into this project would break our current deployment. I also don't have the time to make this configurable. I suggest you fork this project and then implement that change yourself.

A quick fix would be to switch out the `has_any_role` check with the `has_permissions` check. See [this section](https://discordpy.readthedocs.io/en/stable/ext/commands/api.html?highlight=has_any_role#discord.ext.commands.has_permissions) of the Discord.py documentation for more info.
